version: '3'

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: INFO
    ports:
      - "2181:2181"
    #volumes:
    #  - ./zookeeper-1/conf:/etc/kafka/
    #  - ./zookeeper-1/logs:/logs
    #  - ./zookeeper-1/data:/var/lib/zookeeper/data
    #  - ./zookeeper-1/datalog:/var/lib/zookeeper/log/
    networks:
      static-network:
        ipv4_address: 10.2.0.2

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    ports:
      - "9092:9092"
      - "29092:29092"
    #volumes:
    #  - ./kafka-1/logs:/var/log/kafka
    #  - ./kafka-1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper-1
    networks:
      static-network:
        ipv4_address: 10.2.0.3

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16